### ISSUE TITLE
‘Null’ accessories 

### ISSUE THREAD

**Issue by dkahia** [edc1591/homebridge-bond#14]
I bought my Bond the last week of December 2018. I installed the Bond plugin and configured my credentials according to the sample json config. My first ceiling fan partially loaded with some switches available, but some were labeled ‘null’, and all the other ceiling fans also showed ‘null’ (the word null) descriptions. No devices were controlled in any way via Homekit.

I’ve tried several times to get things working. I’ve uninstalled and loaded version 1.1. I’ve reinstalled 2.0. I’ve deleted all my fans, and added them back again with different names, even one at a time. I’ve deleted the cachedAccessories file numerous times. I have two different fan controller modules and tried one of each alone.  I noticed that the bond firmware seems to have been updated from 1.117 to 1.130, so retried with no change.  The broken devices cause Homebridge to crash, so currently the plugin is not installed. 

I recall seeing a notice the first week of January saying there was a server glitch and to rerun discovery on Alexa to fix it. I am not sure if that glitch would have impacted Homebridge loading the devices, but assume that could be the case. Deleting the cachedAccessories file seems to stop Homebridge from logging that it is loading Bond accessories from cache. 

Any other suggestions to get this working?

**Comment by iRayanKhan** [comment]
Did you try removing the bridge from homekit, persist and accessory folder?

**Comment by dkahia** [comment]
I have not tried removing Homebridge from Homekit. I assume I will need to redo all my automation after re-adding Homebridge? Also, I am not clear on what you mean by “persist and accessory folder”.

**Comment by iRayanKhan** [comment]
Yes you will have to redo the automations and those folder are in the .homebridge folder

**Comment by dkahia** [comment]
I managed to get a few more Bond devices to apprear in Homekit. It’s seems that they are loading with names reflecting the Bond app location values rather than the names assigned in the Bond app. Even still, I am getting a few with ‘null’ in their name. The ones that load with proper looking values still won’t respond when activating their switches, and Homebridge crashes. 

I’m attempting to set up a new instance of Homebridge on another VM to see if I can get it working.

**Comment by dkahia** [comment]
Fresh Linux VM, NodeJS, Homebridge and only the Bond plugin. Four ceiling fans in Bond, and all  assigned unique locations, even if they didn’t correspond to places in the house. Fired up Homebridge and added the bridge to Homekit. All 4 devices were added to Homekit, one named Master Bedroom, two named Playroom and one named “null”.  Bond location values of Lounge and Portable must have translated to Playroom and “null”. No idea which is which since I can’t test. Activating any device via Homekit causes the Homebridge instance to crash with the first indication of the error talking about “callback”. The Bond hardware doesn’t flash, so the command must have died out in the cloud. The Bond IOS app controls the 4 devices.

**Comment by plainsane** [comment]
Can you post the stack trace?

**Comment by plainsane** [comment]
I’ve been looking at this off and on, I had a bunch of null devices show up one day after a restart...looks like I’m getting them back via their rest api.

**Comment by plainsane** [comment]
> I managed to get a few more Bond devices to apprear in Homekit. It’s seems that they are loading with names reflecting the Bond app location values rather than the names assigned in the Bond app. Even still, I am getting a few with ‘null’ in their name. The ones that load with proper looking values still won’t respond when activating their switches, and Homebridge crashes.
> 
> I’m attempting to set up a new instance of Homebridge on another VM to see if I can get it working.

Yea, the null names are coming back from their api.  It’s undocumented api so there might be a better way.  For now just rename them in the home app

**Comment by dkahia** [comment]
> Can you post the stack trace?

Do you still want a stack trace?  I’d need some instructions to pull it for you.

**Comment by dkahia** [comment]
> > I managed to get a few more Bond devices to apprear in Homekit. It’s seems that they are loading with names reflecting the Bond app location values rather than the names assigned in the Bond app. Even still, I am getting a few with ‘null’ in their name. The ones that load with proper looking values still won’t respond when activating their switches, and Homebridge crashes.
> > I’m attempting to set up a new instance of Homebridge on another VM to see if I can get it working.
> 
> Yea, the null names are coming back from their api. It’s undocumented api so there might be a better way. For now just rename them in the home app

I thought the nulls might be causing Homebridge to crash. Doesn’t matter if I rename them, they don’t do anything except cause the Homebridge server to crash. That’s one of the reasons I set up a separate VM to test this plugin. Based on what I can read of the log, the callback function seems to be the cause - part if it scrolls off the top of the screen.

**Comment by dkahia** [comment]
![91403251-3F59-423B-B3BD-3FAA6197F710](https://user-images.githubusercontent.com/47283213/54095262-85f8a900-4363-11e9-8e6b-6a1b86d2a883.jpeg)

**Comment by dkahia** [comment]
Seems that the Avahi Library was either not installed or not installed properly. Installed, and it seems to working on the testing VM. Next, I’ll review the original VM and plan to get the Bond plugin working there. 

Hoping that this plugin will be updated to the new local API v2 and that it will resolve the issue with the device names coming in as null.
